version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    environment:
      - MONGO_URI=mongodb://root:example@database:27017/tcc_database?authSource=admin
    depends_on:
      - database
    volumes:
      - ./backend:/app
      - /app/node_modules

# Serviço do frontend
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8081:8081"

  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   environment:
  #     - REACT_NATIVE_PACKAGER_HOSTNAME=localhost
  #   depends_on:
  #     - backend  # Somente se houver um backend como dependência

  database:
    image: mongo
    # command: ["--verbosity", "1"]
    ports:
      - "27017:27017"
    volumes:
      - ./database/mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

